#!/bin/bash

TYPE=${1:-debug}

BUILD=${2:-mqt}

[ "$TYPE" = "debug" ] || SILENT="--enable-silent-rules"

if [ $BUILD = 'mqt' ]; then
    ./configure --with-boost=/opt/env/prod/Boost/Current \
        --with-boost-libdir=/opt/env/prod/Boost/Current/gcc/lib \
        --with-thrift=/opt/env/prod/Thrift/Current \
        --with-thrift-libdir=/opt/env/prod/Thrift/Current/gcc/lib \
        --prefix=/opt/pkg/utxx/1.1 \
        --exec-prefix=/opt/pkg/utxx/1.1/gcc \
        ${SILENT} --enable-${TYPE}
else
    ./configure --enable-${TYPE} --with-boost=/opt/boost --prefix=/opt/utxx --with-thrift=/opt/thrift
fi
